import React from "react";
import type { Metadata } from 'next'

import Header from "@/widgets/Header/Header";
import Footer from "@/widgets/Footer/Footer";

export const metadata: Metadata = {
    title: 'Cakes Catalog',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
       <>
           <Header/>
                {children}
           <Footer/>
       </>
    )
}
